Address 7.x-ISLANDORA-1749; fix field linking with sepcial characters…
Islandora/islandora_solr_search pull request #310
Opened 2017-02-22 01:35 UTC by nhart

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1749

# What does this Pull Request do?
Allows linked terms containing special characters to search properly

# What's new?
Escapes special characters based on advanced search regex and replaces forward slashes with ~slsh~

# How should this be tested?
- enable "Escape Lucene special characters" with default regex under http://site.com/admin/islandora/search/islandora_solr/settings > Advanced search block
- enable "link to search" for a particular Solr field containing special characters under http://site.com/admin/islandora/search/islandora_solr/settings > Display fields

- Search for a particular object with said field containing special characters
Clicking on a linked term should perform a proper search and not return a 400 error.

# Additional Notes:
* Does this change require documentation to be updated? possibly?
* Does this change add any new dependencies? No
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? No
* Could this change impact execution of existing code? No

# Interested parties
@Islandora/7-x-1-x-committers @DiegoPino

2017-03-21 21:30 UTC, rosiel requested changes
I can't tell if this is doing what it's supposed to. I tried with five sample strings including various slashes and backslashes. 

I'm gonna try table markdown here... 

|test string	|before this PR	|With this pr, no config changes	|regex enabled|
|---|---|---|---|
|`simple/test`	|fail	|pass	|pass|
|`simple//test	`|fail	|pass	|pass|
|`simple/\test`	|fail	|pass	|fail|
|`simple\\test`	|pass	|pass	|fail|
|`simple.\/test`	|fail	|pass	|fail|

It seemed that good things came out of this PR, except if lucene regex was enabled. 

What's supposed to happen?

2017-03-22 14:54 UTC, DiegoPino commented
@rosiel thanks for reviewing this, just can't find the time right now. You are just great

2017-03-28 19:35 UTC, nhart commented
@rosiel  sorry for the delay. work is busy. life is busy. I will to revisit and verify what the original use case was.

2017-11-24 15:20 UTC, adam-vessey requested changes
I believe we only want the `islandora_solr_replace_slashes()` in the flow, and moving to the configurable regex for escaping this query is probably not desired.

2017-11-24 15:20 UTC, adam-vessey commented on includes/utilities.inc
> +              $linked_value = islandora_solr_facet_query_escape(stripcslashes($original_value), $lucene_regex);
The `stripcslashes()` invocation makes a mess with the backslashes... though really, not sure we want to do the regex thing in this situation: The links we generate are for searches on the exact string value, right? The "regex doodad" is more to allow more permissive escaping in advanced search, intended to allow the use of more Lucene syntax, if desired.

2017-11-24 15:20 UTC, adam-vessey commented on includes/utilities.inc
> +              $linked_value = islandora_solr_facet_query_escape(stripcslashes($original_value), $lucene_regex);
Similarly, the regex stuff is intended to pass the queries slightly different... not wrapping things in quotes: https://github.com/Islandora/islandora_solr_search/blob/53852cc5859edaba910229a3e31d6600f28b65a3/includes/blocks.inc#L761-L767

2017-11-27 16:52 UTC, DiegoPino commented
@nhart this one was solved via https://github.com/Islandora/islandora_solr_search/commit/66549e8d24d88a17a57a73a5ef134969d2a66bee, i guess it's an internal thing of you guys. Let me know if you want to close this one or your pull actually does something different. Thanks!

2017-11-28 13:36 UTC, closed without merging